### ISSUE TITLE
Fullstack-harjoitustyön koodikatselmointi

### ISSUE THREAD

**Issue by ShootingStar91** [Doubleneck/Hillandweb2022#28]
Tämä on katselmointi fullstack-projektistasi. Voit halutessasi hyödyntää tässä annettuja vinkkejä ja parannusehdotuksia, mutta sinun ei tarvitse tehdä muutoksia projektiisi saadaksesi siitä suorituksen.

### Palaute sovelluksesta

+ Sovellus demottiin livenä
+ Sovellus on selkeä ja helppokäyttöinen
+ Tarjoaa tarvittavat toiminnot kuten kuvien, videoiden ja tiedon jakaminen, sekä myös interaktiiviset asiat kuten kappaleen toivominen
+ Sovelluksessa on myös käyttäjän- ja roolienhallintaa, kuten ylläpitäjän tila, josta löytyy enemmän toimintoja

### Palaute koodista 

**Frontend**

+ Koodi on jaoteltu järkevästi eri tiedostoihin ja kansioihin kuten components api-kutsut sisältävä services.
+ Ymmärrettävää Reactia
+ Projektissa on käytetty vanhaa reduxia, mikä tuottaa vähän turhaa boilerplate-koodia. Nykyään kannattaa käyttää Redux Toolkitia, tosin legacy-kirjastot on ymmärrettäviä jos projekti on aloitettu jo kauan sitten.
+ services-kansion tiedostoissa on kaikissa oma paikallinen token-muuttuja, joka täytyy sitten asettaa kaikkiin erikseen. Siistimpi ratkaisu olisi antaa se argumenttina sitä tarvitseville api-kutsuille. Token voisi olla user-objektissa reduxissa tallessa.
+ Ternary-lause [komponentin JSX:ssä](https://github.com/Doubleneck/Hillandweb2022/blob/main/hilland_front/src/components/ArchiveForm.js#L79) helposti sekavoittaa komponenttia. Guard clause tai pienempiin komponentteihin jakaminen on keinoja tällaisen vähentämiseen, eli tässä tapauksessa ennen varsinaista return-lausetta olisi voinut tarkistaa onko isFormVisible false, ja palauttaa vain napin, jos on. Tämä vähentäisi sisennystä ja kompleksisuutta isommasta JSX:stä.

**Backend**

+ Backendissä on käytetty hyvin middlewareja erilaisiin tarkoituksiin kuten autentikaatio ja roolinhallinta
+ Backendissä voisi käyttää express-async-errors npm kirjastoa, joka esitellään fullstackopen-kurssilla. Tämän avulla voisi vähentää try-catch koodia, joka hankaloittaa koodin lukemista.
+ Testit vaikuttavat varsin kattavilta. Hyvä!

Sovellus on  laaja ja käyttää erilaisia teknologioita kuten docker, ja AWS kuvien tallentamiseen. Testejä myös löytyy. Plussaa siitä, että sovellus on tehty oikeaan tarpeeseen! Hyvää työtä!

**Comment by Doubleneck** [comment]
Kiitos palautteesta!

Erinomaisia huomioita kaikki.

**Comment by Doubleneck** [comment]
- [x] FIXED: services-kansion tiedostoissa on kaikissa oma paikallinen token-muuttuja, joka täytyy sitten asettaa kaikkiin erikseen. Siistimpi ratkaisu olisi antaa se argumenttina sitä tarvitseville api-kutsuille. 

- [x] FIXED: Backendissä voisi käyttää express-async-errors npm kirjastoa, joka esitellään fullstackopen-kurssilla. Tämän avulla voisi vähentää try-catch koodia, joka hankaloittaa koodin lukemista.

- [x] FIXED: Removed react symbol from chrome bar.

**Comment by Doubleneck** [comment]
- [x] FIXED: services-kansion tiedostoissa on kaikissa oma paikallinen token-muuttuja, joka täytyy sitten asettaa kaikkiin erikseen. Siistimpi ratkaisu olisi antaa se argumenttina sitä tarvitseville api-kutsuille. 

- [x] FIXED: Backendissä voisi käyttää express-async-errors npm kirjastoa, joka esitellään fullstackopen-kurssilla. Tämän avulla voisi vähentää try-catch koodia, joka hankaloittaa koodin lukemista.

- [x] FIXED: Removed react symbol from chrome bar.
